site_name: My Docs
pages:
- Home: index.md
- User Guide:
    - 'Writing your docs': 'user-guide/writing-your-docs.md'
    - 'Styling your docs': 'user-guide/styling-your-docs.md'
- About:
    - Contributing: about/contributing.md
    - License: about/license.md
theme: Amelia
#license.md
